version: "2"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    links:
      - "db"
    volumes:
      - .:/app

  db:
    image: postgres:9.6.5
    volumes:
      - data-volume:/var/lib/postgresql/data

volumes:
  data-volume:
