default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres

development:
  <<: *default
  database: guardians_destiny_development

test:
  <<: *default
  database: guardians_destiny_test

production:
  <<: *default
  database: guardians_destiny_production
  username: guardians_destiny
  password: <%= ENV['GUARDIANS_DESTINY_DATABASE_PASSWORD'] %>
